version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrations
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/stori?sslmode=disable

  migrations:
    build: .
    command: ["./db_tools", "migrate", "-direction", "up"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/stori?sslmode=disable

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stori
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
