// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID `json:"id"`
	Nickname  string    `json:"nickname"`
	Balance   string    `json:"balance"`
	CreatedAt int64     `json:"created_at"`
	UpdatedAt int64     `json:"updated_at"`
	Active    bool      `json:"active"`
}

type Transaction struct {
	ID          uuid.UUID `json:"id"`
	AccountID   uuid.UUID `json:"account_id"`
	Amount      string    `json:"amount"`
	Type        string    `json:"type"`
	InputFileID string    `json:"input_file_id"`
	InputDate   time.Time `json:"input_date"`
	CreatedAt   int64     `json:"created_at"`
}
